### ISSUE TITLE
this plugin doesn't seem to work in credentials mode

### ISSUE THREAD

**Issue by maoqin** [Kong/kong-plugin-grpc-web#11]
Hello!
  I am using this plugin to expose my grpc api to frontend app with grpc-web protocol. My backend api needs to authorize caller through cookies. However, when I add configure {'withCredentials': true} in my grpc client, any call would fail with browser complaining 
`Response to preflight request doesn't pass access control check: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'. The credentials mode of requests initiated by the XMLHttpRequest is controlled by the withCredentials attribute.`
I found that in the handler.lua code, it explicitly set Access-Control-Allow-Origin to *. Is there any config to changed this behavior?
Thanks very much!

**Comment by javierguerragiraldez** [comment]
Hi @maoqin  Are you using the [gprc-web](https://github.com/grpc/grpc-web) JS library in your frontend?  The current code adds these headers to help it comply with CORS, and because that library does an `OPTIONS` request before RPC calls.

We could add a configuration flag to modify or remove these headers, but I'd prefer to have the code detect a different style of requests, if possible.   The defintion of the `withCredentials` is a bit open ended, so I'm not sure which would be a simple and reliable way to determine it from the first request.

**Comment by gszr** [comment]
@maoqin Could you try out @javierguerragiraldez's PR and report if it solves the issue?

**Comment by gszr** [comment]
@maoqin Did you get a chance to test the PR #14? Thanks!
